name: Practice2

on:
  #push: 
  workflow_dispatch:

jobs: 

  ubutu:
    name: This job is running on ubutu latest runner
    runs-on: ubuntu-latest
    steps:
      - name: step1 for ubutu
        run: date
        

  window:
    name: This job is running on window runner
    runs-on: window-latest
    steps:
      - name: window
        run: date
        
  
  macos:
    name: This job is running on macos runner
    runs-on: mac-latest
    steps:
      - name: macos
        run: date +"%Y-%m-%d %H:%M:%S"

        

  job4:
    name: Job four
    runs-on: ubuntu-latest
    steps:
      - name: step1 for job4
        run: date +"%Y-%m-%d %H:%M:%S"
